# Generated by Django 3.2 on 2024-05-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='codigo',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
