# Generated by Django 3.2 on 2023-10-01 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingregistros',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='trackingregistros',
            name='guia_remision',
        ),
        migrations.AlterField(
            model_name='trackingregistros',
            name='tramo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.tramos'),
        ),
    ]
