# Generated by Django 3.2 on 2023-10-06 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20231001_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('rfuser_cre', models.IntegerField()),
                ('fecha_cre', models.DateField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'pesos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrackingDestinatarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='trackingregistros',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracking.trackingdestinatarios'),
        ),
        migrations.AddField(
            model_name='trackingregistros',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracking.trackingestado'),
        ),
    ]
